### ISSUE TITLE
Fail to setup due to patch files applied with an incorrect order

### ISSUE THREAD

**Issue by ducktyper** [marketplacer/magento2-plugin-seller#3]
#  🐛 Fail to setup

### Steps to re-produce:
1. Clone this project to Magento2 src `app/code/Marketplacer/Seller`
2. Setup `bin/magento setup:upgrade`

### Results:
The setup fails with the message below
```
Unable to apply data patch Marketplacer\Seller\Setup\Patch\Data\AssignGeneralSellerToAllProducts for module Marketplacer_Seller. Original exception message: General Seller Id is not initialized at config param marketplacer_seller/general/general_seller_id
```

### Problem:
Found that there are 4 patch files applied during the setup located in `Setup/Patch/Data`
```
CreateMarketplacerSellerListingUrlRewrites.php
CreateMarketplacerSellerProductAttribute.php
AssignGeneralSellerToAllProducts.php
CreateGeneralSellerEntity.php
```
Currently it seems that `CreateMarketplacerSellerProductAttribute` is applied before `CreateGeneralSellerEntity` which leads to an error.

**Comment by vasiliy-samoilichenko-ewave** [comment]
Revalidated on new Magento installation. Can confirm incorrect dependency existed, but not in the mentioned file.
Fixed by adding one more patch dependency for the patch file AssignGeneralSellerToAllProducts.php.

Will be fixed Fixed within the following commit of the release branch:
https://github.com/marketplacer/magento2-plugin-seller/pull/4/commits/49b501d0a4c54e5283cbebe199837408aebff90e
